name: Auto Release Main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PAT }}             
          tag: "v${{ github.run_number }}"
          name: "Release ${{ github.run_number }}"
          body: "自动生成 release，包含 main 分支的全部内容"
          draft: false
          prerelease: false